config/routes.rb
Dvdverleih::Application.routes.draw do
  resources :searches

  resources :dvds

 devise_for :users
 resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/pages/kontakt"=>"pages#kontakt"
  match "/pages/impressum"=>"pages#impressum"
  match "/pages/formular"=>"pages#formular"

end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
	has_many :users
end

app/models/search.rb
class Search < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :dvds
	has_many :searches
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_friendly_id :name, :use_slug => true, :strip_non_ascii => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  # GET /dvds
  # GET /dvds.xml
  def index
    @dvds = Dvd.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dvds }
    end
  end

  # GET /dvds/1
  # GET /dvds/1.xml
  def show
    @dvd = Dvd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dvd }
    end
  end

  # GET /dvds/new
  # GET /dvds/new.xml
  def new
    @dvd = Dvd.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dvd }
    end
  end

  # GET /dvds/1/edit
  def edit
	@dvd = Dvd.find(params[:id])
  end

  # POST /dvds
  # POST /dvds.xml
  def create
    @dvd = Dvd.new(params[:dvd])
	@dvd.userid = ""
	@dvd.verliehen = 0
    respond_to do |format|
      if @dvd.save
		
        format.html { redirect_to(@dvd, :notice => 'Dvd erfolgreich erstellt.') }
        format.xml  { render :xml => @dvd, :status => :created, :location => @dvd }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dvd.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dvds/1
  # PUT /dvds/1.xml
  def update
    @dvd = Dvd.find(params[:id])
	@dvdusers = @dvd.userid.split(', ')
	@x = 0
	
	while @x < @dvdusers.size
		if @dvdusers[@x] == current_user.id.to_s
			alreadylent = true
		end
		@x = @x + 1
	end
	if user_signed_in?
		if alreadylent != true
			@dvd.verliehen = @dvd.verliehen + 1
			if @dvd.userid == ""
				@dvd.userid = "#{current_user.id}"
			else
				@dvd.userid = "#{@dvd.userid}, #{current_user.id}"
			end
			respond_to do |format|
				if @dvd.update_attributes(params[:dvd])
					format.html { redirect_to(@dvd, :notice => 'Dvd wurde erfolgreich ausgeliehen.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @dvd.errors, :status => :unprocessable_entity }
				end
			end
		else
#			@x = 0
#			@dvd.userid = ""
#			@dvd.verliehen = @dvd.verliehen - 1
#			while @x < @dvdusers.size
#				if current_user.id.to_s == @dvdusers[@x]
		#			@dvdusers.delete(@x)
		#		elsif @dvd.userid = ""
		#			@dvd.userid = "#{@dvdusers[@x]}"
		#		else
		#			@dvd.userid = "#{@dvd.userid}, #{@dvdusers[@x]}"
		#		end
		#		@x = @x + 1
		#	end
			respond_to do |format|
			if @dvd.update_attributes(params[:dvd])
				format.html { redirect_to(@dvd, :notice => 'DVD wurde schon von ihnen ausgeliehen') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @dvd.errors, :status => :unprocessable_entity }
			end
			end
		end
	else
		respond_to do |format|
		if @dvd.update_attributes(params[:dvd])
			format.html { redirect_to(@dvd, :notice => 'Log In notwendig, um DVDs auszuleihen!') }
			format.xml  { head :ok }
		else
			format.html { render :action => "edit" }
			format.xml  { render :xml => @dvd.errors, :status => :unprocessable_entity }
		end
		end
	end

    
  end

  # DELETE /dvds/1
  # DELETE /dvds/1.xml
  def destroy
    @dvd = Dvd.find(params[:id])
    @dvd.destroy

    respond_to do |format|
      format.html { redirect_to(dvds_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.xml
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.xml
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
    
    @dvds = Dvd.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dvds }
    end
  end

  # POST /searches
  # POST /searches.xml
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to(@search, :notice => 'Search was successfully created.') }
        format.xml  { render :xml => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.xml
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to(edit_search_path, :notice => 'Search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.xml
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to(searches_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dvds_helper.rb
module DvdsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dvds/_form.html.erb
<%= form_for(@dvd) do |f| %>
  <% if @dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% @dvd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :verliehen %><br />
    <%= f.check_box :verliehen %>
  </div>
  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dvds/edit.html.erb
<%if user_signed_in? %>   
	<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
		<h1>DVD editieren</h1>
<%= form_for(@dvd) do |f| %>
  <% if @dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% @dvd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beschreibung %><br />
    <%= f.text_field :beschreibung %>
  </div>
  <div class="field">
    <%= f.label :anzahl %><br />
    <%= f.text_field :anzahl %>
  </div>
  <div class="actions">
    <%= f.submit "speichern"%>
  </div>
<% end %>
	<% else %>
		<h1>DVD ausleihen</h1>
	<% end %>
	<%= form_for(@dvd) do |f| %>
  	  <% if @dvd.errors.any? %>
    	<div id="error_explanation">
      	  <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      	  <ul>
      	    <% @dvd.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
      	    <% end %>
      	  </ul>
    	</div>
  	  <% end %>
  
    <div class="actions">
      <%= f.submit "ausleihen" %>
  	</div>
  <% end %>

  <%= link_to 'Info', @dvd %> |
  <%= link_to 'Zurück', dvds_path %>

<% else %>
Bitte logge dich ein!
<% end %>

app/views/dvds/index.html.erb
<h1>Listing dvds</h1>

<table>
  <tr>
	<th></th>
    <th>Name</th>
	<th>Beschreibung</th>
	<% if user_signed_in? %>
	<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
		<th>Verliehen</th>
		<th>Userids</th>
	<% end %>
	<% end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dvds.each do |dvd| %>
  <tr>
    <td><%= dvd.name %></td>
	<td><%= dvd.beschreibung %></td>
	<% if user_signed_in? %>
		<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
			<td><%= dvd.verliehen %></td>
			<td><%= dvd.userid %></td>
		<% end %>
	<% end %>
    <td><%= link_to 'Info', dvd %></td>
	<% if dvd.verliehen != nil %>
	<% if dvd.verliehen < dvd.anzahl %>
		<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
			<td><%= link_to 'Editieren', edit_dvd_path(dvd) %></td>
		<% else %>
			<td><%= link_to 'Ausleihen', edit_dvd_path(dvd) %></td>
		<% end %>
	<% else %>
		<td>Ausleihen</td>
	<% end %>
	<% else %>
		<td><%= link_to 'Ausleihen', edit_dvd_path(dvd) %></td>
	<% end %>
	<% if user_signed_in? %>
		<td><% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
			<%= link_to 'Loeschen', dvd, :confirm => 'Sicher?', :method => :delete %></td>
		<% end %>
	<% end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
	<% if current_user.role == "admin" %>
		<%= link_to 'Neue DVD', new_dvd_path %>
	<% end %>
<% end %>

app/views/dvds/new.html.erb
<%if user_signed_in? %>   
  <% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>

<h1>New dvd</h1>

<%= form_for(@dvd) do |f| %>
  <% if @dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% @dvd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field" height=100>
    <%= f.label :beschreibung %><br />
    <%= f.text_field :beschreibung %>
  </div>
  <div class="field" width=32>
    <%= f.label :anzahl  %><br />
    <%= f.text_field :anzahl %>
  </div>
  <div class="field" width=32>
    <%= f.label :bild  %><br />
    <%= f.text_field :bild %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', dvds_path %>


<% else %>

	Nicht zulässig!

  <% end %>
<% else %>
Bitte logge dich ein!
<% end %>

app/views/dvds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dvd.name %>
</p>

<p>
  <b>Beschreibung:</b>
  <%= @dvd.beschreibung %>
</p>
<% if user_signd_in? %>
	<% if current_user.role = "admin" || current_user.role = "mitarbeiter" %>
		<p>
			<b>Userid:</b>
			<%= @dvd.userid %>
		</p>
		<p>
			<b>Anzahl:</b>
			<%= @dvd.anzahl %>
		</p>
		<p>
			<b>Verliehen:</b>
			<%= @dvd.verliehen %>
		</p>
	<% end %>
<% end %>


<%= link_to 'Edit', edit_dvd_path(@dvd) %> |
<%= link_to 'Back', dvds_path %>

app/views/layouts/_search.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>
  
  <p><%= f.label :search %> <br />
  <%= f.password_field :search%></p>

  <p><%= f.submit "Update" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dvd-Verleih</title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
<%= image_tag("banner.jpg", :alt => "Haw Erotik", :class => "round") %>
</div>

<div id="navigation">
Home &nbsp;&nbsp; Kategorien &nbsp;&nbsp; Account &nbsp;&nbsp; Abmelden         


</div>

<div id="content">
<%= yield %>
</div>

<div id="footer">
<%= link_to "Impressum" , pages_impressum_path %> <%= link_to "Kontakt" , pages_kontakt_path %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Dvdverleih</h1>
<% if user_signed_in? %>
	<% if current_user.role == "admin" %>
	<p><%= link_to "View List of Users", users_path %></p>
	<% end %>
<% end %>
<p><%= link_to "DVD-Liste", dvds_path %></p>


<% if user_signed_in? %>
  <li>
  <%= link_to('abmelden', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('anmelden', new_user_session_path)  %>  
  </li>
<% end %>


<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>


#User show muss naziegen ob dvds verliehen wurden
#Suche aufsetzen

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :words %><br />
    <%= f.text_field :words %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<table>
  <tr>
    <th>Name</th>
	<th>Beschreibung</th>
	<% if user_signed_in? %>
	<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
		<th>Verliehen</th>
		<th>Userids</th>
	<% end %>
	<% end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dvds.each do |dvd| %>
  <% if dvd.name == @search.words %>

  <tr>
    <td><%= dvd.name %></td>
	<td><%= dvd.beschreibung %></td>
	<% if user_signed_in? %>
		<% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
			<td><%= dvd.name %></td>
			<td><%= dvd.userid %></td>
		<% end %>
	<% end %>
    <td><%= link_to 'Info', dvd %></td>
    <td><%= link_to 'Ausleihen', edit_dvd_path(dvd) %></td>
	<% if user_signed_in? %>
		<td><% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>
			<%= link_to 'Loeschen', dvd, :confirm => 'Sicher?', :method => :delete %></td>
		<% end %>
	<% end %>
  </tr>
<% end %> 
<% end %> 
</table>

<br />
<% if user_signed_in? %>
	<% if current_user.role == "admin" %>
		<%= link_to 'Neue DVD', new_dvd_path %>
	<% end %>
<% end %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Words</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.words %></td>
    <td><%= search.user_id %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Words:</b>
  <%= @search.words %>
</p>

<p>
  <b>User:</b>
  <%= @search.user_id %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/users/index.html.erb
<%if user_signed_in? %>   
  <% if current_user.role == "admin" || current_user.role == "mitarbeiter" %> 

	<h1>Users</h1>
	<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
    </tr>
  <% end %>
  </table>

  <% else %>

	Nicht zulässig!

  <% end %>
<% else %>
Bitte logge dich ein!
<% end %>

app/views/users/show.html.erb
<%if user_signed_in? %>   
  <% if current_user.role == "admin" || current_user.role == "mitarbeiter" %>

	<h1><%= @user.name %></h1>
	<p><%= @user.email %></p>
	<br />
	<p><%= link_to 'Edit', edit_user_registration_path %></p>
	<p><%= link_to 'List of Users', users_path %></p>

  <% else %>

	Nicht zulässig!

  <% end %>
<% else %>
Bitte logge dich ein!
<% end %>